services:
  postgres:
    image: "postgres:15.3"
    container_name: tarefas
    environment:
      POSTGRES_DB: agenda
      POSTGRES_USER: agendauser
      POSTGRES_PASSWORD: 1234 
    ports:
      - "5432:5432"
    restart: always